services:
  react:
    container_name: react
    image: react
    build:
      dockerfile: ./srcs/react/Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - react-volume:/var/
    restart: always
  postgressql:
    container_name: postgressql
    image: postgressql
    build:
      dockerfile: ./srcs/postgressql/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always

volumes:
  react-volume:
    driver_opts:
      o: bind
      type: bind
      device: /home/ksuh/goinfre/ft_tc
  db-volume:
    driver_opts:
      o: bind
      type: bind
      device: /home/ksuh/goinfre/data/postgressql
