# Generated by Django 5.1.4 on 2024-12-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ranking_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_games',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
