# Generated by Django 5.1.4 on 2024-12-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tournament_tournamentplayer_tournament_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='player',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentPlayer',
        ),
    ]
