# Generated by Django 5.1.4 on 2024-12-16 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tournamentplayer_tournament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('round_sum', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('ONGOING', '진행중'), ('COMPLETED', '완료'), ('CANECLLED', '취소됨')], default='PENDING', max_length=20)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_winner', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('score', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('ONGOING', '진행중'), ('COMPLETED', '완료'), ('CANECLLED', '취소됨')], default='PENDING', max_length=20)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_losses', to='api.user')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player1_matches', to='api.user')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player2_matches', to='api.user')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='api.user')),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
                'unique_together': {('tournament', 'round_number', 'match_number')},
            },
        ),
    ]
