# Generated by Django 5.1.4 on 2024-12-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tournament_current_people_tournament_max_people'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentMatch',
            new_name='Match',
        ),
    ]
