# Generated by Django 5.1.4 on 2024-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_tournamentmatch_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='round_sum',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
