# Generated by Django 5.1.4 on 2024-12-17 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tournament_round_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('ONGOING', '진행중'), ('COMPLETED', '완료'), ('CANECELLED', '취소됨')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('ONGOING', '진행중'), ('COMPLETED', '완료'), ('CANECELLED', '취소됨')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
