# Generated by Django 5.1.4 on 2024-12-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_match_status_alter_match_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
